### ISSUE TITLE
讨论帖 的 db schema 缺失

### ISSUE THREAD

**Issue by fdkevin0** [bangumi/dev-env#15]
缺失的有条目讨论回复、小组讨论回复等
看起来是同一个数据结构的样子，应该是类似 `chii_index_comments` 这样吧
`chii_index_comments` 又是啥的回复呢

**Comment by trim21** [comment]
chii_index_comments是目录评论 https://bgm.tv/index/36778/comments

**Comment by trim21** [comment]
条目讨论和小组讨论回复应该是有的吧，具体是哪个表我忘了

**Comment by trim21** [comment]
条目讨论贴是这个

https://github.com/bangumi/dev-env/blob/master/sql/schema/chii_subject_topics.sql

小组是这个

https://github.com/bangumi/dev-env/blob/master/sql/schema/chii_group_topics.sql

**Comment by fdkevin0** [comment]
不是讨论 是讨论回复，按data的内容看，两个存储在不同表内，讨论回复看起来是存在类似目录评论的结构的表中

**Comment by trim21** [comment]
回复跟主题讨论存在了同一张表里....我没记错的话

**Comment by trim21** [comment]
哦我记错了- -
条目的讨论回复在 `chii_subject_posts` 表中

**Comment by trim21** [comment]
小组的在`chii_group_posts`

**Comment by trim21** [comment]
https://github.com/bangumi/dev-env/pull/4
