### ISSUE TITLE
ci 测试中 mysql 初始化检测无效

### ISSUE THREAD

**Issue by fdkevin0** [bangumi/dev-env#17]
看起来 `mysqladmin ping` 并不可靠，初始化阶段就可以ping，但是实际上无法访问数据库
https://github.com/bangumi/dev-env/blob/b577b1868059835d227720daf20df52ddb6c5b9c/wait_mysql_ready.sh#L5
https://stackoverflow.com/a/53717981

**Comment by trim21** [comment]
。看起来是因为数据sql文件越来越多了，加载的时间也变长了，所以之前没遇到这个问题

**Comment by trim21** [comment]
你参照SO这个问题修改一下这个wait脚本？

**Comment by fdkevin0** [comment]
好的

**Comment by fdkevin0** [comment]
看起来连的上数据库并不代表初始化完成，而且比ping还快的样子。
大概还是需要检查下数据库表的数量？
明天再搞了

**Comment by trim21** [comment]
表的数量是硬性要求，没法减吧…

**Comment by fdkevin0** [comment]
我的意思是检查生成表的数量和sql数是否对的上

**Comment by fdkevin0** [comment]
或许可以加个sql最后执行来标记初始化完成？

**Comment by fdkevin0** [comment]
检查 logs 里是否有这一句输出吧
https://github.com/docker-library/mysql/blob/32aecb725b28afa043a5e879977a7947dfb64c14/5.7/docker-entrypoint.sh#L394

**Comment by fdkevin0** [comment]
应该可以了，mysql容器的启动过程有点蛋疼，第一次启动后开始初始化，然后再`shutdown`，再启动
现在是先检查日志里初始化完成，再检查是否允许连接

**Comment by trim21** [comment]
这个wait_mysql_ready.sh要暴露出去给别的仓库用的，好像还是有你说的这个问题啊

**Comment by fdkevin0** [comment]
没写在wait_mysql_ready.sh里，我改下
